apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    purpose: replica
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: dev
      project: roboshop
      purpose: rs-demo
  template:
    metadata:
      labels:
        project: roboshop
        purpose: rs-demo
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl