apiVersion: v1
kind: ConfigMap
metadata:
  name: config-pod
  labels:
    environment: dev
    env: dev
data:
  Course: "devops with aws" 
---

apiVersion: v1
kind: Pod
metadata:
  name: env-configmap
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: config-pod