apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  username: "c2FtZWVyCg=="
  password: "c2FtZWVyMTIzCg=="

---

apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret